### ISSUE TITLE
SQL_Script_for SAP_HANA Data Model script 03_Fill_Tables_EN.sql entries created in German, and not English

### ISSUE THREAD

**Issue by p19priya** [captainabap/SQLScript_for_SAP_HANA#1]
Hello,
SQL_Script_for SAP_HANA Data Model script 03_Fill_Tables_EN.sql creates entries in tables in German, and not English, which dosen't help actually. I guess this script is intended to create entries in English (EN). This appears to be a bug. 
Please can this issue be looked into, so we are able to learn SAP HANA with the data model examples ?
Thanks

**Comment by captainabap** [comment]
Hi p19priya, 
thank you for the first issue in this repository. Can you tell me exactly which table you mean?
Thank you & merry christmas, 
JB

**Comment by p19priya** [comment]
Hi, thanks for your response. The issue appears to be majorly in the 'tasks' table entries being created by the SQL script 01_Create_Tables_EN.sql as part of SQL_Script_for_SAP_HANA which contains all the SQL scripts to create a data model. 
Thanks for your help and Merry Christmas !
Regards.

**Comment by captainabap** [comment]
Hi P19priya, 

this is just a placeholder text. It is not german, but nonsensical, improper Latin.  Please have a look at https://en.wikipedia.org/wiki/Lorem_ipsum
The content doesn't matter for the examples in the book. 

Regards, 
JB

**Comment by p19priya** [comment]
Hi, thanks for the clarification, I got it now. It really helps. 
Best Regards.

**Comment by p19priya** [comment]
And thank you very much for your help ! Merry Christmas. 
Best Regards.
